# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "smtr"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ configdbt(...) }}` macro.
models:
  smtr:
    # Config indicated by + and applies to all files under models/example/
    br_rj_riodejaneiro_brt_estacoes:
      +materialized: view
      schema: br_rj_riodejaneiro_brt_estacoes
    br_rj_riodejaneiro_brt_gps:
      +materialized: view
      schema: br_rj_riodejaneiro_brt_gps
    br_rj_riodejaneiro_geo:
      +materialized: view
      schema: br_rj_riodejaneiro_geo
    br_rj_riodejaneiro_gtfs:
      +materialized: view
      schema: br_rj_riodejaneiro_gtfs
    br_rj_riodejaneiro_gtfs_brt:
      +materialized: view
      schema: br_rj_riodejaneiro_gtfs_brt
    br_rj_riodejaneiro_gtfs_planned:
      +materialized: view
      schema: br_rj_riodejaneiro_gtfs_planned
    br_rj_riodejaneiro_onibus_gps:
      +materialized: view
      schema: br_rj_riodejaneiro_onibus_gps
    br_rj_riodejaneiro_rdo:
      +materialized: view
      schema: br_rj_riodejaneiro_rdo
    br_rj_riodejaneiro_sigmob:
      +materialized: view
      schema: br_rj_riodejaneiro_sigmob
    br_rj_riodejaneiro_transporte:
      +materialized: view
      schema: br_rj_riodejaneiro_transporte
    br_rj_riodejaneiro_veiculos:
      +materialized: view
      schema: br_rj_riodejaneiro_veiculos
    brt_manutencao:
      +materialized: view
      schema: brt_manutencao
    projeto_multa_automatica:
      +materialized: view
      schema: projeto_multa_automatica

vars:
  # IdModalSMTR
  # 22 -> SPPO
  # 23 -> SPPO Executivo
  id_modal_smtr: ["'22'", "'23'"]

  # Filtro de velocidade no cálculo de viagens realizadas
  ## Serão consideradas somente velocidades entre os valores abaixo
  filtro_min_velocidade: 10 # viagens_realizadas
  filtro_max_velocidade: 90 # viagens_realizadas

  # Parametros de intercecção do ônibus com rota
  ## Tamanho do buffer da rota
  tamanho_buffer_metros: 100 # aux_registros_intersec /flag_trajeto_correto
  ## buffer em torno dos pontos iniciais e finais dos shapes
  buffer_inicio_fim_metros: 250 # aux_registros_intersec
  ## Intervalo máximo que um veículo pode ficar dentro da rota para ser considerado
  ## dentro da rota. Afeta a flag flag_trajeto_correto_hist
  intervalo_max_desvio_segundos: 600 # flag_trajeto_correto
  ## Intervalo mínimo de detecção de saída de viagem
  faixa_horaria_minutos: 5 # aux_registros_intersec
  ## velocidade mínima para que o carro seja considerado em movimento em aux_registros_velocidade
  velocidade_limiar_parado: 3
  ## velocidade máxima média que o veículo pode atingir para evitar outliers provenientes de túneis
  velocidade_maxima: 60
  ## janela sobre a qual a média móvel da velocidade é calculada em aux_registros_velocidade
  janela_movel_velocidade: 600
  ## distância mínima para que o veículo seja identificado parado em um terminal ou garagem em aux_registros_parada
  distancia_limiar_parada: 250

  # Data de início do sigmob
  ## Todos os dados anteriores a esta data serão comparados com ela
  ## Dados posteriores serão comparados por dia.
  data_inclusao_agency: "2021-08-03"
  data_inclusao_stop_times: "2021-08-03"
  data_inclusao_linhas: "2021-08-03"
  data_inclusao_routes: "2021-08-03"
  data_inclusao_trips: "2021-08-03"
  data_inclusao_shapes: "2021-08-24"
  data_inclusao_stops: "2021-08-24"
  data_inclusao_calendar: "2021-09-30"
  data_inclusao_frota_determinada: "2021-09-30"
  data_inclusao_stop_details: "2021-09-30"
  date_start: "2021-08-01 00:00:00"

  # Tamanho da faixa horária da aplicação da multa em minutos
  # ATENÇÃO: esse campo afeta a `hora_pico`
  faixa_horaria: 10

  # Estabilidade das capturas

  ## Número mínimo de sucessos dentro da faixa horária para a API
  ## ser considerada ativa.
  ## variável afetada: flag_falha_api
  n_minimo_sucessos_api: 0

  ## Número mínimo de sucessos dentro da faixa horária para a
  ## captura ser considerada ativa.
  ## variável afetada: flag_falha_capturas_smtr
  n_minimo_sucessos_captura: 8

  # Multas

  ## Número de carros em que a mudança de regras acontece.
  ## Quando o número de carros é menor ou igual ao `limiar_frota_determinada`,
  ## a frota operante deve ser igual a determinada.
  ## Quando o número de carros é maior, então as regras são baseadas em frações
  ## da frota determinada.
  limiar_frota_determinada: 5

  ## Intervalo dos picos por consórcio
  # Para adicionar novo consórcio, basta coloca-lo na lista
  # Os minutos são faixas horárias proporcionais ao parametro `faixa_horaria`
  # Portanto, para uma faixa horária de 10 minutos o minuto 50 representa o
  # intervalo de 50 até 59 minutos
  hora_pico:
    intersul:
      manha:
        inicio:
          hora: 6
          minuto: 30
        fim:
          hora: 9
          minuto: 20
      tarde:
        inicio:
          hora: 16
          minuto: 0
        fim:
          hora: 18
          minuto: 50
    internorte:
      manha:
        inicio:
          hora: 6
          minuto: 0
        fim:
          hora: 8
          minuto: 50
      tarde:
        inicio:
          hora: 16
          minuto: 0
        fim:
          hora: 18
          minuto: 50
    transcarioca:
      manha:
        inicio:
          hora: 6
          minuto: 0
        fim:
          hora: 8
          minuto: 50
      tarde:
        inicio:
          hora: 16
          minuto: 0
        fim:
          hora: 18
          minuto: 50
    santa cruz:
      manha:
        inicio:
          hora: 5
          minuto: 30
        fim:
          hora: 8
          minuto: 20
      tarde:
        inicio:
          hora: 17
          minuto: 0
        fim:
          hora: 19
          minuto: 50

  ## Proporções da frota determinada por dia da semana
  proporcao_dia_util: 0.8
  proporcao_sabado: 0.5
  proporcao_domingo: 0.4

  ## Multa de faixas horárias não consecutivas
  multa_nao_consecutiva:
    valor: 8 # número de faixas horárias não consecutivas
    descricao: pelo menos 80 minutos não consecutivos operando abaixo da frota esperada
    artigo: 017.I
    prioridade: 2

  ## Multa de faixas horárias consecutivas
  multa_consecutiva:
    valor: 3 # número de faixas horárias consecutivas (válido somente para ímpares)
    descricao: pelo menos 30 minutos consecutivos operando abaixo da frota esperada
    artigo: 017.I
    prioridade: 3

  ## Multa X horas sem carros (NÃO CONSIDERADO)
  multa_horas_sem_carros:
    valor: 24 # número de faixas horárias sem carros
    descricao: 24 horas consecutivas operando sem carros
    artigo: 017.VII
    prioridade: 1

  ## Multa GPS 120 minutos (NÃO CONSIDERADO)
  multa_gps_120_minutos:
    valor: 120 # minutos
    descricao: 120 minutos com a API fora do ar
    artigo: 017.X

  ## Multa GPS 1 dia (NÃO CONSIDERADO)
  multa_gps_1_dia:
    valor: 1440 # minutos
    descricao: 1 dia com a API fora do ar
    artigo: 017.IX

  # dependências de views/tabelas
  agency: "rj-smtr.br_rj_riodejaneiro_sigmob.agency"
  calendar: "rj-smtr.br_rj_riodejaneiro_sigmob.calendar"
  codigos_consorcios: rj-smtr.br_rj_riodejaneiro_transporte.codigos_consorcios
  frota_determinada: "rj-smtr.br_rj_riodejaneiro_sigmob.frota_determinada"
  limites_caixa: "rj-smtr.br_rj_riodejaneiro_geo.limites_geograficos_caixa"
  linhas: "rj-smtr.br_rj_riodejaneiro_sigmob.linhas"
  linhas_sppo: rj-smtr.br_rj_riodejaneiro_transporte.linhas_sppo
  onibus_registros: "rj-smtr.br_rj_riodejaneiro_onibus_gps.registros"
  onibus_registros_logs: rj-smtr.br_rj_riodejaneiro_onibus_gps.registros_logs
  polygon_garagem: "rj-smtr.br_rj_riodejaneiro_geo.garagens_polygon"
  routes: "rj-smtr.br_rj_riodejaneiro_sigmob.routes"
  shapes: "rj-smtr.br_rj_riodejaneiro_sigmob.shapes"
  stop_details: "rj-smtr.br_rj_riodejaneiro_sigmob.stop_details"
  stop_times: "rj-smtr.br_rj_riodejaneiro_sigmob.stop_times"
  stops: "rj-smtr.br_rj_riodejaneiro_sigmob.stops"
  terminais: "rj-smtr.br_rj_riodejaneiro_transporte.terminais_onibus_coordenadas"
  trips: "rj-smtr.br_rj_riodejaneiro_sigmob.trips"
