default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: rj-smtr-dev
      dataset: dbt_test
      threads: 2
      keyfile_json:
        type: "{{ env_var('DBT_CREDENTIALS_TYPE') }}"
        project_id: "{{ env_var('DBT_CREDENTIALS_PROJECT_ID') }}"
        private_key_id: "{{ env_var('DBT_CREDENTIALS_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('DBT_CREDENTIALS_PRIVATE_KEY') }}"
        client_email: "{{ env_var('DBT_CREDENTIALS_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('DBT_CREDENTIALS_CLIENT_ID') }}"
        auth_uri: "{{ env_var('DBT_CREDENTIALS_AUTH_URI') }}"
        token_uri: "{{ env_var('DBT_CREDENTIALS_TOKEN_URI') }}"
        auth_provider_x509_cert_url: "{{ env_var('DBT_CREDENTIALS_PROVIDER_CERT_URL') }}"
        client_x509_cert_url: "{{ env_var('DBT_CREDENTIALS_CLIENT_CERT_URL') }}"
