para cada carro a cada 10 mintuos 
vehicle_id, linha, timestamp_inicio, ,
[{
  'linha': 'bleble'
  'trip_id': 'balbalba',
  'is_begging': False,
  'is_end': True,
  'count': 4,
},
{
  'trip_id': 'balbalba',
  'is_begging': False,
  'is_end': True,
  'count': 4,
}]

-->

definir buffer em metros para shape

linha == linha
linha != linha --> pegar ultimos 30 minutos e checar quais shapes batem


--> registros_tratada
