# Lista de views do dataset
# Atributos de cada view:
# - name: nome sem terminação .sql ou .yaml
# - materialized: true|false para materializar ou não
# - depends_on: lista de views das quais ela depende
views:
  registros_tratada_8_dias:
    materialized: false
    depends_on:
      [
        br_rj_riodejaneiro_geo.limites_geograficos_caixa,
        br_rj_riodejaneiro_brt_gps.registros_filtrada,
      ]

  registros_filtrada:
    materialized: false
    depends_on:
      [
        br_rj_riodejaneiro_geo.limites_geograficos_caixa,
        br_rj_riodejaneiro_brt_gps.registros,
      ]

  aux_registros_velocidade_carro:
    materialized: false
    depends_on: [br_rj_riodejaneiro_brt_gps.registros_filtrada]

  aux_registros_velocidade_status:
    materialized: false
    depends_on:
      [
        br_rj_riodejaneiro_transporte.estacoes_e_terminais_brt,
        br_rj_riodejaneiro_transporte.garagens,
        br_rj_riodejaneiro_brt_gps.aux_registros_velocidade_carro,
      ]
  registros_velocidade_carro:
    materialized: false
    depends_on:
      [
        br_rj_riodejaneiro_brt_gps.registros_filtrada,
        br_rj_riodejaneiro_brt_gps.aux_registros_velocidade_status,
      ]

  registros_flag_trajeto_correto:
    materialized: false
    depends_on: [br_rj_riodejaneiro_brt_gps.registros_filtrada]

  registros_tratada:
    materialized: true
    depends_on:
      [
        br_rj_riodejaneiro_brt_gps.registros_velocidade_carro,
        br_rj_riodejaneiro_brt_gps.registros_flag_trajeto_correto,
      ]

# Definição de taxa de atualização
scheduling:
  cron: "0 * * * *"

# Definição de particionamento
# - column: nome da coluna
# - type: deve ser um dos seguintes
#   * DATE (não exige período)
#   * DATE_TRUNC (exige período MONTH/YEAR)
#   * DATETIME_TRUNC (exige período DAY/HOUR/MONTH/YEAR)
#   * TIMESTAMP_TRUNC (exige período DAY/HOUR/MONTH/YEAR)
#   * <To-do> RANGE_BUCKET
#   * <To-do> GENERATE_ARRAY
# - period: período (conforme especificado acima)
partitioning:
  column: "column_name"
  type: "DATE"
  period: ""

# Parâmetros da query
parameters:
  param_name: "param_value"

# Parâmetros de backfill
backfill:
  # Formato %Y-%m-%d %H:%M:%S
  start_timestamp: "2021-01-01 00:00:00"
