# Definição de taxa de atualização
scheduling:
  cron: "0 * * * *"
# Parâmetros de backfill
backfill:
  # Formato %Y-%m-%d %H:%M:%S
  start_timestamp: "2021-03-01 00:00:00"

  # Definição de particionamento
# - column: nome da coluna
# - type: deve ser um dos seguintes
#   * DATE (não exige período)
#   * DATE_TRUNC (exige período MONTH/YEAR)
#   * DATETIME_TRUNC (exige período DAY/HOUR/MONTH/YEAR)
#   * TIMESTAMP_TRUNC (exige período DAY/HOUR/MONTH/YEAR)
#   * <To-do> RANGE_BUCKET
#   * <To-do> GENERATE_ARRAY
# - period: período (conforme especificado acima)
partitioning:
  column: "data"
  type: ""
  period: ""

# Parâmetros da query
parameters:
  # dependências de views/tabelas
  registros_filtrada: "rj-smtr-dev.br_rj_riodejaneiro_brt_gps.aux_registros_filtrada"
  velocidade: "rj-smtr-dev.br_rj_riodejaneiro_brt_gps.aux_registros_velocidade" # registros_tratada
  parada: "rj-smtr-dev.br_rj_riodejaneiro_brt_gps.aux_registros_parada" # registros_tratada
  flag_trajeto_correto: "rj-smtr-dev.br_rj_riodejaneiro_brt_gps.aux_registros_flag_trajeto_correto" # registros_tratada

# Lista de views do dataset
# Atributos de cada view:
# - name: nome sem terminação .sql ou .yaml
# - materialized: true|false para materializar ou não
# - depends_on: lista de views das quais ela depende
views:
  gps_brt:
    materialized: true
    depends_on:
      - br_rj_riodejaneiro_brt_gps._aux_registros_filtrada
      - br_rj_riodejaneiro_brt_gps.aux_registros_velocidade
      - br_rj_riodejaneiro_brt_gps.aux_registros_flag_trajeto_correto
      - br_rj_riodejaneiro_brt_gps.aux_registros_parada
  gps_sppo:
    materialized: true
    depends_on:
      - br_rj_riodejaneiro_onibus_gps._aux_registros_filtrada
      - br_rj_riodejaneiro_onibus_gps.aux_registros_velocidade
      - br_rj_riodejaneiro_onibus_gps.aux_registros_flag_trajeto_correto
      - br_rj_riodejaneiro_onibus_gps.aux_registros_parada
