# TODO: Write CI pipeline
# -> Get all changed files https://github.com/marketplace/actions/get-all-changed-files
# -> For each changed file, upload it to GCS (use secrets)

name: Update queries

on:
  push:
    branches:
      - "master"

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  update:
    name: Update queries for modified files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup gcloud / gsutil
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}

      - name: Sync views
        run: |
          gsutil rsync -ru views/ gs://$GCS_BUCKET/queries/views/

      - name: Sync materialized views
        run: |
          gsutil rsync -ru materialized_views/ gs://$GCS_BUCKET/queries/materialized_views/
