# TODO: Write CI pipeline
# -> Get all changed files https://github.com/marketplace/actions/get-all-changed-files
# -> For each changed file, upload it to GCS (use secrets)

name: Update queries

on:
  push:
    branches:
      - "master"

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  update:
    name: Update queries for modified files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: files
        name: Get modified files
        uses: jitterbit/get-changed-files@v1

      - name: Setup gcloud / gsutil
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}

      - name: Upload modified files
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ ${{ changed_file }} == *.sql ]]
            then
              echo "File ${changed_file} has been modified, uploading..."
              gsutil cp ${changed_file} gs://$GCS_BUCKET/queries/
            fi
          done
